import requests
import time

API_URL = "http://localhost:8001"
task_id = "demo"

articles = {
    "001": "Tencent Intelligent Mobility is working on integrating SoundHound Chat AI Automotive, the most advanced in-vehicle voice assistant on the market, to give drivers and passengers access to a range of apps, car controls, and entertainment domains (including major audiovisual streaming services) – as well as LLM-powered generative AI responses – just through natural speech. This partnership between SoundHound AI and Tencent Intelligent Mobility demonstrates the commitment on behalf of both companies to providing localized, high-quality voice AI solutions for a vast range of global markets. Currently, SoundHound provides solutions to a range of automakers globally in over 25 languages. SoundHound will participate in the 2025 TIME DAY, Tencent Intelligent Mobility Ecosystem Day, on April 22, 2025. Tom Park, the company’s VP of Asia-Pacific Business Development, Automotive, will join the “Globalization Deep-dive” Sub-forum panel to discuss how building local ecosystems can drive global growth.",
    "002": "The collaboration addresses the technical challenges in measuring game performance with rendering acceleration, moving beyond traditional metrics of average frame rate and stability. The new Frame Generation index enables real-time visualization of post-acceleration frame rate data generated by Pixelworks' rendering solutions, helping developers and OEMs identify rendering bottlenecks more precisely. In the current era of rapid development of mobile games, high frame rates have become pivotal for both developers and players. Smartphone manufacturers also seek to enhance the end user experience by increasing the frame rate of mobile games utilizing various approaches, the most effective of which is by incorporating a dedicated hardware rendering accelerator. However, due to technical challenges associated with accurately and consistently measuring game performance with rendering acceleration activated, traditional mobile game performance testing is typically conducted based purely on the average frame rate and frame stability of a game. As a result, a majority of today's existing testing standards prevent the industry from benefiting from a more precise and complete optimization of mobile gaming performance.",
    "003": "Hero Esports, a Chinese esports powerhouse backed by Tencent Holdings and Saudi Arabian video-gaming giant Savvy Games Group, is betting big on artificial intelligence (AI) to streamline operations and become a global industry leader, the CEO said in an interview. We are pilot-testing several AI models, including DeepSeek, in all aspects of the business,” said Danny Tang, co-founder and CEO of Hero Esports. The company is also adapting a local version of DeepSeek to analyse patents and historical contracts to identify areas that might “require more attention”, she said. The company’s adoption of AI ties into China’s efforts to dominate the global video-gaming arena. Over the past couple of decades, the sector has transformed into a cultural and economic juggernaut."
}

print("===> Enqueuing tasks")
for article_id, text in articles.items():
    resp = requests.post(f"{API_URL}/enqueue", json={
        "task_id": task_id,
        "article_id": article_id,
        "text": text
    })
    print(f"Sent: {article_id}, status: {resp.status_code}")

print("===> Polling")
all_done = False
while not all_done:
    resp = requests.get(f"{API_URL}/status/{task_id}", params=[
        ("article_ids", aid) for aid in articles.keys()
    ])
    data = resp.json()
    print(data)
    # exit(0)
    all_done = True
    for a in data["articles"]:
        print(f"[{a['article_id']}] Status: {a['status']}")
        if a["status"] not in ["done", "failed"]:
            all_done = False

    if not all_done:
        print("Waiting 2 seconds...")
        time.sleep(2)
print("===> All tasks done")