version: "3.8"
services:

  redis:
    image: redis:6.2
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nlp_task
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

  nlp-task-dispatcher:
    build: ./nlp-task-dispatcher
    container_name: nlp-dispatcher
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/nlp_task?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    restart: on-failure

  python-crawler:
    build: ./python-crawler
    container_name: crawler
    ports:
      - "8002:8002"
    depends_on:
      - redis
    restart: unless-stopped

  python-nlp:
    build: ./python-nlp
    container_name: nlp
    ports:
      - "8001:8001"
    depends_on:
      - redis
    restart: unless-stopped

volumes:
  mysql_data:
